Numpy,Pandas --> Data Visualization (Matplotlib,Seaborn and Plotly)

Exploratory Data Analysis (EDA) -->It is the process of Examining,Summarizing and Transforming the data and making it ready for Machine learning modeling and Statistical Analysis..

Objectives of EDA:

-->Cleaning the data
-->Handling missing values
-->Identifying the patterns in the data
-->Detecting Outliers in the data
-->Performing Data Visualization

Exploratory Data Analysis (EDA) is the process of examining, understanding, and summarizing data before applying Machine Learning or Statistical Models.
EDA helps identify patterns, trends, missing values, outliers, and relationships within data.

=
Exploratory Data Analysis (EDA) is the process of analyzing datasets using statistical and visualization techniques to understand the structure and quality of the data.

Objectives of EDA
• Understand the dataset. • Identify missing values. • Detect outliers. • Find patterns and trends. • Discover relationships between variables. • Prepare data for Machine Learning.

Why is EDA Important?
• Improves data quality. • Helps make better decisions. • Reduces modeling errors. • Reveals hidden insights. • Increases model accuracy.

Applications of EDA

• Data Science • Machine Learning • Business Analytics • Market Research • Financial Analysis • Healthcare Analytics

In [1]:
#Import the libraries
import numpy as np
import pandas as pd

In [2]:
#EDA --> Census Income Dataset --> Kaggle,UCI
data = pd.read_csv('/content/adult.csv')
data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [3]:
#First we need to understand the data -->loading the data -->basic information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
#get individual info from columns
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [5]:
data.shape;data.size

488415

In [6]:
#to display the defined number of samples (head,tail)
data.head() #default it returns 5 samples
data.head(15)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,216864,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,Private,150601,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K
7,74,State-gov,88638,Doctorate,16,Never-married,Prof-specialty,Other-relative,White,Female,0,3683,20,United-States,>50K
8,68,Federal-gov,422013,HS-grad,9,Divorced,Prof-specialty,Not-in-family,White,Female,0,3683,40,United-States,<=50K
9,41,Private,70037,Some-college,10,Never-married,Craft-repair,Unmarried,White,Male,0,3004,60,?,>50K
10,45,Private,172274,Doctorate,16,Divorced,Prof-specialty,Unmarried,Black,Female,0,3004,35,United-States,>50K
11,38,Self-emp-not-inc,164526,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,0,2824,45,United-States,>50K
12,52,Private,129177,Bachelors,13,Widowed,Other-service,Not-in-family,White,Female,0,2824,20,United-States,>50K
13,32,Private,136204,Masters,14,Separated,Exec-managerial,Not-in-family,White,Male,0,2824,55,United-States,>50K
14,51,?,172175,Doctorate,16,Never-married,?,Not-in-family,White,Male,0,2824,40,United-States,>50K

In [7]:
data.tail()
data.tail(10)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
32551,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32552,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32553,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32554,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32555,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [8]:
data.sample();
data.sample(5)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
13355,51,Self-emp-not-inc,171924,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
18721,35,Private,283305,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
12234,21,Private,198431,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Female,0,0,40,United-States,<=50K
23590,90,Private,52386,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K
1905,30,Self-emp-inc,321990,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,15024,0,60,?,>50K

In [9]:
#Description of data
data.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [10]:
#get description for object columns
#dir(data.describe())
data.describe(include= 'object')

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

In [11]:
#fetch only numeric columns separate
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [12]:
#from numpy._core.multiarray import dtype
#data.columns(dtype='object')

In [13]:
data.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education.num      int64
marital.status    object
occupation        object
relationship      object
race              object
sex               object
capital.gain       int64
capital.loss       int64
hours.per.week     int64
native.country    object
income            object
dtype: object

In [14]:
#separate int and object columns
data.select_dtypes(include = np.int64)
data.select_dtypes(include = 'object')

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
0,?,HS-grad,Widowed,?,Not-in-family,White,Female,United-States,<=50K
1,Private,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,United-States,<=50K
2,?,Some-college,Widowed,?,Unmarried,Black,Female,United-States,<=50K
3,Private,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,United-States,<=50K
4,Private,Some-college,Separated,Prof-specialty,Own-child,White,Female,United-States,<=50K
...,...,...,...,...,...,...,...,...,...
32556,Private,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,United-States,<=50K
32557,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32558,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32559,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32560,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K

Data Cleaning - 1 : Handling Inconsistencies

In [15]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [16]:
data['workclass']
#To get unique values from the feature
print(data['workclass'].unique())
print(len(data['workclass'].unique()))

['?' 'Private' 'State-gov' 'Federal-gov' 'Self-emp-not-inc' 'Self-emp-inc'
 'Local-gov' 'Without-pay' 'Never-worked']
9

In [17]:
print(data['education'].unique())
print(len(data['education'].unique()))

['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm' 'Assoc-voc' '1st-4th' '5th-6th'
 '12th' '9th' 'Preschool']
16

In [18]:
print(data['marital.status'].unique())
print(len(data['marital.status'].unique()))

['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']
7

In [19]:
print(data['occupation'].unique())
print(len(data['occupation'].unique()))

['?' 'Exec-managerial' 'Machine-op-inspct' 'Prof-specialty'
 'Other-service' 'Adm-clerical' 'Craft-repair' 'Transport-moving'
 'Handlers-cleaners' 'Sales' 'Farming-fishing' 'Tech-support'
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']
15

In [20]:
print(data['race'].unique())
print(len(data['race'].unique()))

['White' 'Black' 'Asian-Pac-Islander' 'Other' 'Amer-Indian-Eskimo']
5

In [21]:
print(data['sex'].unique())
print(len(data['sex'].unique()))

['Female' 'Male']
2

In [22]:
print(data['relationship'].unique())
print(len(data['relationship'].unique()))

['Not-in-family' 'Unmarried' 'Own-child' 'Other-relative' 'Husband' 'Wife']
6

In [23]:
print(data['native.country'].unique())
print(len(data['native.country'].unique()))

['United-States' '?' 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan' 'India'
 'Philippines' 'Trinadad&Tobago' 'Canada' 'South' 'Holand-Netherlands'
 'Puerto-Rico' 'Poland' 'Iran' 'England' 'Germany' 'Italy' 'Japan' 'Hong'
 'Honduras' 'Cuba' 'Ireland' 'Cambodia' 'Peru' 'Nicaragua'
 'Dominican-Republic' 'Haiti' 'El-Salvador' 'Hungary' 'Columbia'
 'Guatemala' 'Jamaica' 'Ecuador' 'France' 'Yugoslavia' 'Scotland'
 'Portugal' 'Laos' 'Thailand' 'Outlying-US(Guam-USVI-etc)']
42

In [24]:
print(data['income'].unique())
print(len(data['income'].unique()))

['<=50K' '>50K']
2

In [25]:
#Finding missing values in the dataset
#data.isnull().sum()
type(data['workclass'].values)

numpy.ndarray

In [28]:
data['workclass']

0              ?
1        Private
2              ?
3        Private
4        Private
          ...
32556    Private
32557    Private
32558    Private
32559    Private
32560    Private
Name: workclass, Length: 32561, dtype: object

#apply replace for below column
replace ? with nan (Not a Number) or desired value which conveys information

In [29]:
data["workclass"] = data.workclass.str.strip()

In [31]:
data['workclass'] = data.workclass.replace('?',np.nan)

In [32]:
data['workclass'].unique()

array([nan, 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [33]:
#Handle the extra spaces
data['education'] = data['education'].str.strip()

In [34]:
#same way we can check for other columns
data['occupation'] = data['occupation'].str.replace('?','other')
data['occupation'].unique()

array(['other', 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [35]:
data['native.country'] = data['native.country'].str.replace('?','notavail')
data['native.country'].unique()

array(['United-States', 'notavail', 'Mexico', 'Greece', 'Vietnam',
       'China', 'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago',
       'Canada', 'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland',
       'Iran', 'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras',
       'Cuba', 'Ireland', 'Cambodia', 'Peru', 'Nicaragua',
       'Dominican-Republic', 'Haiti', 'El-Salvador', 'Hungary',
       'Columbia', 'Guatemala', 'Jamaica', 'Ecuador', 'France',
       'Yugoslavia', 'Scotland', 'Portugal', 'Laos', 'Thailand',
       'Outlying-US(Guam-USVI-etc)'], dtype=object)

In [36]:
#we want to remove all extra in all object columns at a time
#Anonymous functions --> lambda params : expression
data = data.apply(lambda l : l.str.strip() if l.dtype == 'object' else l)

In [37]:
#Removing spaces together is very important to understand about the data
data.select_dtypes(include = np.int64)

       age  fnlwgt  education.num  capital.gain  capital.loss  hours.per.week
0       90   77053              9             0          4356              40
1       82  132870              9             0          4356              18
2       66  186061             10             0          4356              40
3       54  140359              4             0          3900              40
4       41  264663             10             0          3900              40
...    ...     ...            ...           ...           ...             ...
32556   22  310152             10             0             0              40
32557   27  257302             12             0             0              38
32558   40  154374              9             0             0              40
32559   58  151910              9             0             0              40
32560   22  201490              9             0             0              20

[32561 rows x 6 columns]

In [38]:
print(data['hours.per.week'].unique())
print(len(data['hours.per.week'].unique()))

[40 18 45 20 60 35 55 76 50 42 25 32 90 48 15 70 52 72 39  6 65 12 80 67
 99 30 75 26 36 10 84 38 62 44  8 28 59  5 24 57 34 37 46 56 41 98 43 63
  1 47 68 54  2 16  9  3  4 33 23 22 64 51 19 58 53 96 66 21  7 13 27 11
 14 77 31 78 49 17 85 87 88 73 89 97 94 29 82 86 91 81 92 61 74 95]
94

In [39]:
print(data['age'].unique())
print(len(data['age'].unique()))

[90 82 66 54 41 34 38 74 68 45 52 32 51 46 57 22 37 29 61 21 33 49 23 59
 60 63 53 44 43 71 48 73 67 40 50 42 39 55 47 31 58 62 36 72 78 83 26 70
 27 35 81 65 25 28 56 69 20 30 24 64 75 19 77 80 18 17 76 79 88 84 85 86
 87]
73

EDA- 2 : Indexing and Querying

we can use loc and iloc

In [40]:
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,other,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,other,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [41]:
#Query to get 1 to 6 columns
data.loc[1:6]

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,other,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,216864,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,Private,150601,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K

In [42]:
data.loc[1:6][['age','education']]

   age     education
1   82       HS-grad
2   66  Some-college
3   54       7th-8th
4   41  Some-college
5   34       HS-grad
6   38          10th

In [43]:
data.iloc[1:6][['age','education']]

   age     education
1   82       HS-grad
2   66  Some-college
3   54       7th-8th
4   41  Some-college
5   34       HS-grad

In [44]:
#using iloc instead column names use as below
data.iloc[1:6,0:4]

   age workclass  fnlwgt     education
1   82   Private  132870       HS-grad
2   66       NaN  186061  Some-college
3   54   Private  140359       7th-8th
4   41   Private  264663  Some-college
5   34   Private  216864       HS-grad

In [45]:
#Filtering the data
#Get the values of age > 20
data.age;
data['age'][data.age > 20]

0        90
1        82
2        66
3        54
4        41
         ..
32556    22
32557    27
32558    40
32559    58
32560    22
Name: age, Length: 30151, dtype: int64

In [46]:
#Get the values of age > 20 and less than 70
data.age[(data.age > 20) & (data.age < 70)]

2        66
3        54
4        41
5        34
6        38
         ..
32556    22
32557    27
32558    40
32559    58
32560    22
Name: age, Length: 29522, dtype: int64

In [47]:
#try filtering with same above age with marital status
#Age with education and native country
#Age with income and race
#Income>=50k with education

In [48]:
# Query: Print Age & Marital-status column with all the records with age < 20 | age > 70
data.columns;
data[(data.age < 20) | (data.age > 70)][['age','marital.status']]

       age      marital.status
0       90             Widowed
1       82             Widowed
7       74       Never-married
44      71  Married-civ-spouse
46      71  Married-civ-spouse
...    ...                 ...
32502   18       Never-married
32506   71  Married-civ-spouse
32528   81            Divorced
32541   71  Married-civ-spouse
32544   72  Married-civ-spouse

[2197 rows x 2 columns]

In [49]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [50]:
# Query: Print Age,Marital-status,Education and Income column with all the records with age >25 and age <70
data[(data.age > 25) & (data.age < 70)][['age','marital.status','education','income']]

       age      marital.status     education income
2       66             Widowed  Some-college  <=50K
3       54            Divorced       7th-8th  <=50K
4       41           Separated  Some-college  <=50K
5       34            Divorced       HS-grad  <=50K
6       38           Separated          10th  <=50K
...    ...                 ...           ...    ...
32554   32       Never-married       Masters  <=50K
32555   53  Married-civ-spouse       Masters   >50K
32557   27  Married-civ-spouse    Assoc-acdm  <=50K
32558   40  Married-civ-spouse       HS-grad   >50K
32559   58             Widowed       HS-grad  <=50K

[25521 rows x 4 columns]

In [51]:
#count of values in income column
data['income'].unique();
data['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [52]:
data['education'].value_counts(ascending=True)

education
Preschool          51
1st-4th           168
5th-6th           333
Doctorate         413
12th              433
9th               514
Prof-school       576
7th-8th           646
10th              933
Assoc-acdm       1067
11th             1175
Assoc-voc        1382
Masters          1723
Bachelors        5355
Some-college     7291
HS-grad         10501
Name: count, dtype: int64

In [53]:
data['marital.status'].value_counts()

marital.status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [54]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [55]:
data[(data.age < 20)][['income','age']]

      income  age
241    <=50K   19
301    <=50K   19
314    <=50K   19
319    <=50K   19
1087   <=50K   19
...      ...  ...
32368  <=50K   18
32410  <=50K   18
32450  <=50K   19
32457  <=50K   17
32502  <=50K   18

[1657 rows x 2 columns]

In [56]:
data.income.value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [57]:
data.head();
data.tail()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [58]:
#where() function usage -> conditional usage
data.income.where(data.age > 25).to_frame();
data.income.where(data.age > 25,'25K').to_frame() #here if data.age < 25 we are asssuming it to be filled
#with given desired value as by default it takes np.NaN

      income
0      <=50K
1      <=50K
2      <=50K
3      <=50K
4      <=50K
...      ...
32556    25K
32557  <=50K
32558   >50K
32559  <=50K
32560    25K

[32561 rows x 1 columns]

In [59]:
#sort_values --> will return sorted order for the given numerical object
data.sort_values('age');
data.sort_values('age',ascending=False)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,other,Not-in-family,White,Female,0,4356,40,United-States,<=50K
21192,90,Private,84553,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
3854,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K
2296,90,Private,46786,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,9386,0,15,United-States,>50K
2299,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386,0,50,Ecuador,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27615,17,Private,238628,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,5,United-States,<=50K
22755,17,Private,121425,11th,7,Never-married,Adm-clerical,Own-child,White,Female,0,0,16,United-States,<=50K
14986,17,Private,163836,10th,6,Never-married,Sales,Own-child,White,Female,0,0,12,United-States,<=50K
4731,17,Private,242718,11th,7,Never-married,Sales,Own-child,White,Male,0,0,12,United-States,<=50K
32035,17,Private,24090,HS-grad,9,Never-married,Exec-managerial,Own-child,White,Female,0,0,35,United-States,<=50K

EDA : 3 --> Statistical Analysis

In [60]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [61]:
data['hours.per.week'].value_counts();
#Total sum of hours per week
print(data['hours.per.week'].sum())

1316684

In [62]:
#Average of hours per week
print(data['hours.per.week'].mean())

40.437455852092995

In [63]:
print(data['hours.per.week'].median())

40.0

In [64]:
print(data['hours.per.week'].mode())

0    40
Name: hours.per.week, dtype: int64

In [65]:
print(data['workclass'].mode())

0    Private
Name: workclass, dtype: object

In [66]:
data['workclass'].value_counts();
print(data['occupation'].mode())

0    Prof-specialty
Name: occupation, dtype: object

In [67]:
#let us try to group marital-status with age
data.groupby('marital.status').age.mean()

marital.status
Divorced                 43.041639
Married-AF-spouse        32.478261
Married-civ-spouse       43.247596
Married-spouse-absent    40.578947
Never-married            28.150988
Separated                39.354146
Widowed                  58.975831
Name: age, dtype: float64

In [68]:
data.groupby('education').age.mean()

education
10th            37.429796
11th            32.355745
12th            32.000000
1st-4th         46.142857
5th-6th         42.885886
7th-8th         48.445820
9th             41.060311
Assoc-acdm      37.381443
Assoc-voc       38.553546
Bachelors       38.904949
Doctorate       47.702179
HS-grad         38.974479
Masters         44.049913
Preschool       42.764706
Prof-school     44.746528
Some-college    35.756275
Name: age, dtype: float64

In [69]:
data.groupby('occupation').age.mean();
data.groupby('income').age.mean()

income
<=50K    36.783738
>50K     44.249841
Name: age, dtype: float64

In [70]:
#Standarad Deviation along with Variance
data['hours.per.week'].std()

12.347428681730833

In [71]:
data['hours.per.week'].var()

152.4589950504292

In [72]:
#Correlation and Covariance
#if one variable is changing with the other variable
data[['age','hours.per.week']].cov()

                      age  hours.per.week
age             186.06140       11.580130
hours.per.week   11.58013      152.458995

In [73]:
data[['age','hours.per.week']].corr() #by default it is pearson correlation (how the values are
#normally distributed)

                     age  hours.per.week
age             1.000000        0.068756
hours.per.week  0.068756        1.000000

In [74]:
data.columns;
data[['age','hours.per.week','fnlwgt']].corr()

                     age  hours.per.week    fnlwgt
age             1.000000        0.068756 -0.076646
hours.per.week  0.068756        1.000000 -0.018768
fnlwgt         -0.076646       -0.018768  1.000000

In [75]:
# corr() range = -1 to +1
# +ve relation : both in same direction (BF + GF)
# -ve relation : Both go in opposite direction (Husband + wife)
# No relation : when don't know each other

Task : Explore countplot,lineplots,kdeplots over different columns using Seaborn